language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: zGXfBXKMJrYcGIvMVCb7wUTuvp2XJoWLsax3F4ERNNHk8bCeU/YtchVPo/oGGsug3lRJIawC0A4/AO7wOQgtGcDgHaq0a9PT3eioGtwnxtSdxEpPbnMUWuh8TY5Ym9PPNzltvWZElKwaAWGx055dhnhznrglgaNugaZZU+LwJOmqnNGO148tZACU7uHiU3y9QxiQjfDfkwlXa00FX5riSZngEowe2/u3CW4J/4VlpN+CToAoAIJdSoEBs7jcsDfbMEZGN+BnIf/yOjeh8ZAX7IoRRXBo4HQm+VEysCrdo5SmUPruevdOcnPZf5+iCq8k93UsKbeMf5BbLLWhGsoTU5Bud10ObJ3XJht8OpgfNmPHxACvAxjUL5v0DZ2OGQhozoYGQAqXaOTfEiUAPTkLcs9mx7DbgKE58nZiGIAcagacdQRbKyNsvhU6GID5zmXye2DH2c3bpbxDSmiZ1hoFqfU7AsrP0P7czW1gfQKpNxtsLBtj4oRqIsdST8Z6MQukdHxKxMExkLVqdA/dwfPPamvW0XID6keVwbMslLHVpP7YHxhma1j3qvxBEjYqY+IW5CoM3IKxXkvqitGTFV1yiMVocWKpgrr3JnmvpyKFtXMVCLO004ZarwMpkIJIFXzY97Wr4vqERfBT0PCd5TkGNUGoD4TjzYyl+0OmsFD7/ho=
  app: kaitlin-noteful-v3
  on:
    repo: thinkful-ei22/kaitlin-noteful-v3
